=== 81191231/forpdi/backend-java/src/main/resources/forpdi_structure_1.0.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0">
	<xs:simpleType name="DataTypes">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Currency" />
			<xs:enumeration value="DateField" />
			<xs:enumeration value="DateTimeField" />
			<xs:enumeration value="NumberField" />
			<xs:enumeration value="Percentage" />
			<xs:enumeration value="TextArea" />
			<xs:enumeration value="TextField" />
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="Attribute">
		<xs:all>
			<xs:element name="label" type="xs:string" />
			<xs:element name="description" type="xs:string" />
			<xs:element name="type" type="DataTypes" />
		</xs:all>
		<xs:attribute name="required" type="xs:boolean" default="false" />
		<xs:attribute name="visibleInTables" type="xs:boolean" default="true" />
	</xs:complexType>

	<xs:complexType name="StructureLevel">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
			<xs:element name="description" type="xs:string" />
			<xs:element name="attributes">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="attribute" minOccurs="1" maxOccurs="unbounded"
							type="Attribute" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:element name="structure">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="structureName" type="xs:string" />
				<xs:element name="structureDescription" type="xs:string" />
				<xs:element name="structureLevels">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="level" minOccurs="2" maxOccurs="unbounded"
								type="StructureLevel" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== 81191231/forpdi/backend-java/src/main/resources/structure-example.xml
<?xml version="1.0" encoding="UTF-8" ?>
<structure xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="forpdi_structure_1.0.xsd">
	<structureName>PDI Exemplo</structureName>
	<structureDescription>
		Estrutura de exemplo de um PDI de uma Universidade.
	</structureDescription>
	<structureLevels>
		<level>
			<name>Area</name>
			<description>Nível raiz, define as áreas da universidade.</description>
			<attributes>
				<attribute required="true">
					<type>TextField</type>
					<label>Nome</label>
					<description>Nome da Área</description>
				</attribute>
				<attribute required="true">
					<type>TextArea</type>
					<label>Descrição</label>
					<description>Descrição da Área</description>
				</attribute>
			</attributes>
		</level>
		<level>
			<name>Objetivo</name>
			<description></description>
			<attributes>
				<attribute required="true">
					<type>TextField</type>
					<label>Nome</label>
					<description>Nome do Objetivo</description>
				</attribute>
				<attribute required="true">
					<type>TextArea</type>
					<label>Descrição</label>
					<description>Descrição do Objetivo</description>
				</attribute>
			</attributes>
		</level>
		<level>
			<name>Indicador</name>
			<description></description>
			<attributes>
				<attribute required="true">
					<type>TextField</type>
					<label>Nome</label>
					<description>Nome do Indicador</description>
				</attribute>
				<attribute required="true">
					<type>TextArea</type>
					<label>Descrição</label>
					<description>Descrição do Indicador</description>
				</attribute>
			</attributes>
		</level>
		<level>
			<name>Meta</name>
			<description></description>
			<attributes>
				<attribute required="true">
					<type>TextField</type>
					<label>Nome</label>
					<description>Nome da Meta</description>
				</attribute>
				<attribute required="true">
					<type>TextArea</type>
					<label>Descrição</label>
					<description>Descrição da Meta</description>
				</attribute>
			</attributes>
		</level>
	</structureLevels>
</structure>
